### PR TITLE
exclude conflicted classes with custom auth in hive-1.2.1

### PR DESCRIPTION
**Pull request by winnie-altiscale**
## What changes were proposed in this pull request?
To exclude the conflicted classes with custom auth in hive-1.2.1. 

## How was this patch tested?
Tested with the jar in foa and server started successfully and able to access hive table.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Review by alee-altiscale — COMMENTED** [review]
Did the full spark test (run_allxxx) suite pass and verified with the new jar produced? Make sure symlink libs, etc are pointed to the new jar.

**Comment by winnie-altiscale** [comment]
I only replace the jar withtout touching any symlinks.  Ok, running the test now

**Comment by winnie-altiscale** [comment]
run_all_test.kerberos successfully completed.

**Comment by alee-altiscale** [comment]
Looks good. Since we don't need to produce new binaries at the moment, I will merge this on 11/3 evening or early 11/4 morning. The RPM will be produced and tested along with other tickets.

**Comment by alee-altiscale** [comment]
@ganeshr-altiscale when you get a chance, could you take a look to see if this is good to go? thanks.

**Pull request merged**
